# daily running workflow to publish stats to the discord

name: Stats Alert

on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '30 20 * * *'

  workflow_dispatch:

permissions:
  contents: read

jobs:
  setup_environment:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
        ref: ${{ github.event.pull_request.head.sha }}
        fetch-depth: 0
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Generate Statistics
      run: |
        python repo_stats.py

    - name: Send Message Over Discord...
      env:
        DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN}}
        SERVER_ID: ${{ secrets.SERVER_ID}}
        TEXT: daily repo statistics
        IMAGE: stats.png
      run: |
        python repo_stats.py
        python deployment/discordbot.py
        
